version: '3.9'
services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: mariadb-secret
    volumes:
      - /opt/mariadb/data:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d

  postgres:
    image: postgres:14.1
    container_name: postgres
    restart: always
    environment:
      TZ: Asia/Seoul
      POSTGRES_PASSWORD: postgres-secret
    volumes:
      - /opt/postgres/data:/var/lib/postgresql/data
