version: '3.9'
services:
  redis:
    image: redis:6.2
    container_name: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./config:/config
    command: redis-server /config/redis.conf
