// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sample

import (
	"time"
)

type Actor struct {
	ActorID    int32
	FirstName  string
	LastName   string
	LastUpdate time.Time
}
