// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"database/sql"
	"time"
)

type Actor struct {
	ActorID    int32
	FirstName  string
	LastName   string
	LastUpdate time.Time
}

type Address struct {
	AddressID  int32
	Address    string
	Address2   sql.NullString
	District   string
	CityID     int16
	PostalCode sql.NullString
	Phone      string
	LastUpdate time.Time
}

type Category struct {
	CategoryID int32
	Name       string
	LastUpdate time.Time
}

type City struct {
	CityID     int32
	City       string
	CountryID  int16
	LastUpdate time.Time
}

type Country struct {
	CountryID  int32
	Country    string
	LastUpdate time.Time
}

type Customer struct {
	CustomerID int32
	StoreID    int16
	FirstName  string
	LastName   string
	Email      sql.NullString
	AddressID  int16
	Activebool bool
	CreateDate time.Time
	LastUpdate sql.NullTime
	Active     sql.NullInt32
}

type Film struct {
	FilmID          int32
	Title           string
	Description     sql.NullString
	ReleaseYear     interface{}
	LanguageID      int16
	RentalDuration  int16
	RentalRate      string
	Length          sql.NullInt16
	ReplacementCost string
	Rating          interface{}
	LastUpdate      time.Time
	SpecialFeatures []string
	Fulltext        interface{}
}

type FilmActor struct {
	ActorID    int16
	FilmID     int16
	LastUpdate time.Time
}

type FilmCategory struct {
	FilmID     int16
	CategoryID int16
	LastUpdate time.Time
}

type Inventory struct {
	InventoryID int32
	FilmID      int16
	StoreID     int16
	LastUpdate  time.Time
}

type Language struct {
	LanguageID int32
	Name       string
	LastUpdate time.Time
}

type Payment struct {
	PaymentID   int32
	CustomerID  int16
	StaffID     int16
	RentalID    int32
	Amount      string
	PaymentDate time.Time
}

type Rental struct {
	RentalID    int32
	RentalDate  time.Time
	InventoryID int32
	CustomerID  int16
	ReturnDate  sql.NullTime
	StaffID     int16
	LastUpdate  time.Time
}

type Staff struct {
	StaffID    int32
	FirstName  string
	LastName   string
	AddressID  int16
	Email      sql.NullString
	StoreID    int16
	Active     bool
	Username   string
	Password   sql.NullString
	LastUpdate time.Time
	Picture    []byte
}

type Store struct {
	StoreID        int32
	ManagerStaffID int16
	AddressID      int16
	LastUpdate     time.Time
}
