// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"context"
)

type Querier interface {
	GetActor(ctx context.Context, actorID int32) (*Actor, error)
	GetCustomer(ctx context.Context, customerID int32) (*Customer, error)
	GetFilm(ctx context.Context, filmID int32) (*Film, error)
	ListActors(ctx context.Context, arg *ListActorsParams) ([]*Actor, error)
	ListCustomers(ctx context.Context, arg *ListCustomersParams) ([]*Customer, error)
	ListFilms(ctx context.Context, arg *ListFilmsParams) ([]*Film, error)
}

var _ Querier = (*Queries)(nil)
